export const types = {
    CHANGE_TITLE: "CHANGE_TITLE",
    WITH_PARAMS: "WITH_PARAMS",
    VALUE: "VALUE",
    ADD_USER: "ADD_USER",
    DELETE_ALL: "DELETE_ALL",
    ADD_NUMBER: "ADD_NUMBER",
    CLEAR_LIST: "CLEAR_LIST"
}
